"""initial schema

Revision ID: a7821a4243e6
Revises: 
Create Date: 2026-06-12 14:38:12.947658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a7821a4243e6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audit_table_record', table_name='audit_logs')
    op.drop_index('idx_audit_user_time', table_name='audit_logs')
    op.drop_index('idx_assignment_baby', table_name='baby_incubator_assignments')
    op.drop_index('idx_assignment_incubator', table_name='baby_incubator_assignments')
    op.drop_index('uq_active_baby_assignment', table_name='baby_incubator_assignments', postgresql_where="(status = 'active'::assignment_status)")
    op.drop_index('uq_active_incubator_assignment', table_name='baby_incubator_assignments', postgresql_where="(status = 'active'::assignment_status)")
    op.drop_index('idx_monitoring_baby_time', table_name='monitoring_records')
    op.drop_index('idx_monitoring_recorded_by', table_name='monitoring_records')
    op.drop_index('idx_involvement_baby_time', table_name='parent_involvement_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_involvement_baby_time', 'parent_involvement_records', ['baby_id', sa.text('observation_time DESC')], unique=False)
    op.create_index('idx_monitoring_recorded_by', 'monitoring_records', ['recorded_by'], unique=False)
    op.create_index('idx_monitoring_baby_time', 'monitoring_records', ['baby_id', sa.text('observation_time DESC')], unique=False)
    op.create_index('uq_active_incubator_assignment', 'baby_incubator_assignments', ['incubator_id'], unique=True, postgresql_where="(status = 'active'::assignment_status)")
    op.create_index('uq_active_baby_assignment', 'baby_incubator_assignments', ['baby_id'], unique=True, postgresql_where="(status = 'active'::assignment_status)")
    op.create_index('idx_assignment_incubator', 'baby_incubator_assignments', ['incubator_id'], unique=False)
    op.create_index('idx_assignment_baby', 'baby_incubator_assignments', ['baby_id'], unique=False)
    op.create_index('idx_audit_user_time', 'audit_logs', ['user_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_audit_table_record', 'audit_logs', ['table_name', 'record_id'], unique=False)
    # ### end Alembic commands ###
